<div class="bg-white shadow-xl rounded-2xl border border-gray-200 overflow-hidden">
    <div class="bg-gradient-to-r from-blue-50 via-indigo-50 to-purple-50 px-6 py-6 border-b border-gray-200">
        <div class="flex justify-between items-center">
            <div class="flex items-center space-x-4">
                <div class="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg"><span class="text-white font-bold text-lg">RW</span></div>
                <div><h2 class="text-2xl font-bold text-gray-900">Data RW</h2><p class="mt-1 text-sm text-gray-600">Kelola nomor RW berdasarkan dusun sebagai struktur wilayah menengah.</p></div>
            </div>
            <div class="flex items-center gap-3">@permission('rws.create')<button wire:click="$dispatch('openRwForm')" class="group bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-6 py-3 rounded-xl text-sm font-semibold flex items-center shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"><svg class="w-5 h-5 mr-2 group-hover:rotate-90 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>Tambah RW</button>@endpermission</div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
            <div class="group relative bg-white overflow-hidden shadow-lg rounded-2xl border border-gray-200"><div class="absolute inset-0 bg-gradient-to-br from-blue-50 to-transparent"></div><div class="relative p-6"><p class="text-sm font-medium text-gray-600 mb-1">Total RW</p><p class="text-xl font-bold text-gray-900">{{ $stats['total_rws'] }}</p><div class="mt-4 text-sm text-blue-600 font-semibold">Wilayah menengah</div></div></div>
            <div class="group relative bg-white overflow-hidden shadow-lg rounded-2xl border border-gray-200"><div class="absolute inset-0 bg-gradient-to-br from-emerald-50 to-transparent"></div><div class="relative p-6"><p class="text-sm font-medium text-gray-600 mb-1">Dusun Terjangkau</p><p class="text-xl font-bold text-gray-900">{{ $stats['hamlets_covered'] }}</p><div class="mt-4 text-sm text-emerald-600 font-semibold">Sebaran wilayah</div></div></div>
            <div class="group relative bg-white overflow-hidden shadow-lg rounded-2xl border border-gray-200"><div class="absolute inset-0 bg-gradient-to-br from-purple-50 to-transparent"></div><div class="relative p-6"><p class="text-sm font-medium text-gray-600 mb-1">RT Terhubung</p><p class="text-xl font-bold text-gray-900">{{ $stats['total_rts'] }}</p><div class="mt-4 text-sm text-purple-600 font-semibold">Struktur turunan</div></div></div>
        </div>
        <div class="mt-6 flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0 lg:space-x-6"><div class="flex-1"><div class="relative"><div class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none"><svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg></div><input wire:model.live="search" type="text" placeholder="Cari nomor RW atau dusun..." class="block w-full pl-12 pr-4 py-3 border border-gray-300 rounded-xl leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"></div></div><div class="flex flex-col sm:flex-row space-y-3 sm:space-y-0 sm:space-x-4"><select wire:model.live="perPage" class="px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white text-sm font-medium transition-all duration-200"><option value="10">10 per halaman</option><option value="25">25 per halaman</option><option value="50">50 per halaman</option></select></div></div>
    </div>
    <div class="overflow-x-auto"><table class="min-w-full"><thead class="bg-gradient-to-r from-gray-50 to-gray-100"><tr><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider rounded-tl-xl">Dusun</th><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Nomor RW</th><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Jumlah RT</th><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider rounded-tr-xl">Aksi</th></tr></thead><tbody class="bg-white divide-y divide-gray-100">@forelse($rws as $rw)<tr class="hover:bg-gradient-to-r hover:from-blue-50 hover:to-purple-50 transition-all duration-300"><td class="px-6 py-5"><div class="text-sm font-semibold text-gray-900">{{ $rw->hamlet?->name ?? '-' }}</div></td><td class="px-6 py-5"><div class="text-sm text-gray-700">RW {{ $rw->number }}</div></td><td class="px-6 py-5"><span class="inline-flex items-center rounded-xl bg-gradient-to-r from-indigo-100 to-purple-100 px-3 py-1.5 text-xs font-semibold text-indigo-700 shadow-sm">{{ $rw->rts_count }} RT</span></td><td class="px-6 py-5 whitespace-nowrap text-sm font-medium"><div class="flex gap-2">@permission('rws.edit')<button wire:click="$dispatch('openRwForm', { rwId: {{ $rw->id }} })" class="group/btn inline-flex items-center px-3 py-2 text-xs font-semibold text-blue-600 bg-blue-50 rounded-lg hover:bg-blue-100 hover:text-blue-700 transition-all duration-200 transform hover:scale-105">Edit</button>@endpermission @permission('rws.delete')<button wire:click="confirmDeleteRw({{ $rw->id }})" class="group/btn inline-flex items-center px-3 py-2 text-xs font-semibold text-red-600 bg-red-50 rounded-lg hover:bg-red-100 hover:text-red-700 transition-all duration-200 transform hover:scale-105">Hapus</button>@endpermission</div></td></tr>@empty<tr><td colspan="4" class="px-6 py-16 text-center text-gray-500">Belum ada data RW.</td></tr>@endforelse</tbody></table></div>
    <div class="px-6 py-4 bg-gradient-to-r from-gray-50 to-blue-50 border-t border-gray-200 rounded-b-2xl"><div class="flex items-center justify-between"><div class="text-sm text-gray-600">Menampilkan <span class="font-medium">{{ $rws->firstItem() ?? 0 }}</span> sampai <span class="font-medium">{{ $rws->lastItem() ?? 0 }}</span> dari <span class="font-medium">{{ $rws->total() }}</span> RW</div><div class="flex-1 flex justify-center">{{ $rws->links() }}</div></div></div>
</div>
